# Generated by Django 4.0.1 on 2022-01-27 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advantages',
            name='icon',
        ),
    ]
