# Generated by Django 4.0.1 on 2022-01-27 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_advantages_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='categorytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Service Translation'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
