# Generated by Django 4.0.1 on 2022-01-27 22:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_team_teammember_teamtranslation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.CharField(max_length=150)),
                ('telegram', models.EmailField(max_length=150)),
                ('instagram', models.EmailField(max_length=150)),
                ('twitter', models.EmailField(max_length=150)),
                ('bot_token', models.CharField(max_length=200)),
                ('admin_id', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About Us',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Translation', 'Translation')], max_length=100)),
                ('source', models.CharField(choices=[('English', 'English'), ('Deutch', 'Deutch'), ('Russian', 'Russian'), ('French', 'French'), ('Korean', 'Korean'), ('Uzbek', 'Uzbek')], max_length=100)),
                ('target', models.CharField(choices=[('English', 'English'), ('Deutch', 'Deutch'), ('Russian', 'Russian'), ('French', 'French'), ('Korean', 'Korean'), ('Uzbek', 'Uzbek')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'Questions',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Team'},
        ),
        migrations.AlterModelOptions(
            name='teammembertranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Member Translation'},
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='partners')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='app.about')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('question', models.CharField(max_length=155, verbose_name='question')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='answer')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.questions')),
            ],
            options={
                'verbose_name': 'question Translation',
                'db_table': 'app_questions_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BannerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=155, verbose_name='title')),
                ('text', ckeditor.fields.RichTextField(verbose_name='text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.banner')),
            ],
            options={
                'verbose_name': 'Banner Translation',
                'db_table': 'app_banner_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('text', ckeditor.fields.RichTextField(verbose_name='text')),
                ('footer', models.TextField(verbose_name='footer text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.about')),
            ],
            options={
                'verbose_name': 'About Translation',
                'db_table': 'app_about_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
